os: linux
language: python
python:
  - "3.5"
virtualenv:
  system_site_packages: true
addons:
  apt:
    packages:
    - python3-gi                              # GObject
    - gir1.2-gtk-3.0                          # gi.repository.gtk python-xdg
install:
  - pip install -r requirements_travis.txt
script:
  - python -m compileall .
  - pep8 . || true
  - pychecker --no-shadow
    --blacklist gi._glib,gi._gobject,gi._gobject._gobject,GLib,ssl,gobject
    bluewho.py
  - python setup.py install --optimize=1 --root=build
  - ls -laR build
